# Lab 02 - NumPy Exercises 



Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:

zeros_array = np.zeros(10)
print(repr(zeros_array))


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


 Create an array of 10 ones

In [4]:
ones_array = np.ones(10)
print(repr(ones_array))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


 Create an array of 10 fives

In [6]:
import numpy as np

fives_array = np.full(10, 5.0)
print(repr(fives_array))


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


#### Create an array of the integers from 10 to 50

In [9]:


array = np.arange(10, 51)  # Start at 10, stop at 51 (exclusive)
print(repr(array))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])


#### Create an array of all the even integers from 10 to 50

In [11]:
array_even=np.arange (10,51,2)
print(repr(array_even))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])


#### Create a 3x3 matrix with values ranging from 0 to 8

In [35]:

matrix = np.arange(0,9).reshape(3, 3)
print(repr(matrix))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


#### Create a 3x3 identity matrix

In [37]:

identity_matrix = np.eye(3)
print(repr(identity_matrix))


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


#### Use NumPy to generate a random number between 0 and 1

In [18]:

random_number = np.random.rand(1)
print(repr(random_number))

array([0.5385053])


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [19]:

random_array = np.random.randn(25)  # Generate 25 random numbers
print(repr(random_array))


array([ 1.90228404, -2.14534651, -0.77943492,  0.18405828, -1.00602895,
       -0.86905255,  0.46746691, -0.16356141, -0.50789111,  0.23569849,
        1.08534631,  0.35795379, -0.20782227,  2.08792326,  0.54270063,
       -0.59098135, -0.93176688,  0.81774926,  0.60242465, -0.60302831,
        0.66416207, -0.5913713 ,  1.87756253,  0.28887393,  0.98032174])


Create the following matrix:

In [38]:
array = np.arange(1, 101).reshape(10, 10) / 100
print(repr(array))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])


Create an array of 20 linearly spaced points between 0 and 1:

In [39]:

a = np.linspace(0, 1, 20)
print(repr(a))

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [5]:
matrix = np.arange(1,26).reshape(5,5)
print(repr(matrix))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [52]:
output=mat[2:5, 1:5]
print(repr(output))

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [6]:
value = matrix[1:5, 1:3]  
print(repr(value))


array([[ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])


In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [9]:
result = matrix[0:3, 1:2]
print(repr(result))


array([[ 2],
       [ 7],
       [12]])


In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [7]:
result = matrix[4,:]
print(repr(result))


array([21, 22, 23, 24, 25])


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [11]:
output=matrix[3:5, : ]
print(repr(output))

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


### Now do the following

#### Get the sum of all the values in mat

In [10]:
total_sum = np.sum(matrix)
print(total_sum)


325


#### Get the standard deviation of the values in mat

In [30]:
std_dev = np.std(matrix)
print(std_dev)


7.211102550927978


# Great Job!